CREATE DATABASE SalesCarWebPage;
GO

USE SalesCarWebPage;
GO

CREATE TABLE UsersRole(
	UsersRoleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	RoleName NVARCHAR(100) NOT NULL UNIQUE,
	IsActive BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE Brand(
	BrandId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BrandName NVARCHAR(100) NOT NULL,
);
GO

CREATE TABLE [Address](
	AddressId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Street NVARCHAR(100) NOT NULL UNIQUE,
	Street2 NVARCHAR(100) NULL,
	DoorNumber NVARCHAR(50) NOT NULL UNIQUE,
	[Floor] NVARCHAR(50) NULL,
	PostalCode NVARCHAR(20) NOT NULL,
	[Locate] NVARCHAR(100) NOT NULL,
	City NVARCHAR(100) NOT NULL,
	Country NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contact (
    ContactId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PhoneNumber NVARCHAR(20) NOT NULL,
    JobTitle NVARCHAR(100) NULL
);
GO

CREATE TABLE Model(
	ModelId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BrandId INT NOT NULL,
	ModelName NVARCHAR(100) NOT NULL,	
	CONSTRAINT FK_Model_Brand FOREIGN KEY (BrandId) REFERENCES Brand(BrandId),
);
GO

CREATE TABLE Users(
	UserId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ContactId INT NOT NULL, 
    UsersRoleId INT NOT NULL DEFAULT 1,
	[Name] NVARCHAR(255) NOT NULL,
    UserName NVARCHAR(255) NOT NULL UNIQUE,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    ProfilePicture NVARCHAR(MAX) NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Salt NVARCHAR(64) NOT NULL,
    IsApproved BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    LastUpdatedAt DATETIME2 NULL,
    IsActive BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_Users_Contact FOREIGN KEY (ContactId) REFERENCES Contact(ContactId),
    CONSTRAINT FK_Users_UserRole FOREIGN KEY (UsersRoleId) REFERENCES UsersRole(UsersRoleId)
);
GO

CREATE TABLE Provider (
    ProviderId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    AddressId INT NOT NULL,
    NameProvider NVARCHAR(200) NOT NULL,
    NIF NVARCHAR(9) NOT NULL UNIQUE,
    CONSTRAINT FK_Provider_User FOREIGN KEY (UserId) REFERENCES Users(UserId),
    CONSTRAINT FK_Provider_Address FOREIGN KEY (AddressId) REFERENCES [Address](AddressId)
);
GO

CREATE TABLE Client (
    ClientId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    ContactId INT NOT NULL,
    AddressId INT NOT NULL,
    ClientName NVARCHAR(200) NOT NULL,
    NIF NVARCHAR(9) NOT NULL UNIQUE,
    CONSTRAINT FK_Client_User FOREIGN KEY (UserId) REFERENCES Users(UserId),
    CONSTRAINT FK_Client_Contact FOREIGN KEY (ContactId) REFERENCES Contact(ContactId),
    CONSTRAINT FK_Client_Address FOREIGN KEY (AddressId) REFERENCES [Address](AddressId)
);
GO

CREATE TABLE Car (
    CarId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ModelId INT NOT NULL,
    ProviderId INT NOT NULL,
    TypeOfFuel NVARCHAR(100) NOT NULL,
    CarColor NVARCHAR(100) NOT NULL,
    EngineCapacity NVARCHAR(100) NOT NULL,
    CarTare DECIMAL(18,2) NOT NULL,
    CarPrice DECIMAL(18,2) NOT NULL,
    IsAvailable BIT NOT NULL DEFAULT 1,
    PlateNumber NVARCHAR(100) NOT NULL UNIQUE,
    [Year] INT NOT NULL,
    Kilometers INT NOT NULL,
    ImageUrl NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    LastUpdatedAt DATETIME2 NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    IsApproved BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Car_Model FOREIGN KEY (ModelId) REFERENCES Model(ModelId),
    CONSTRAINT FK_Car_Provider FOREIGN KEY (ProviderId) REFERENCES Provider(ProviderId)
);
GO

CREATE TABLE MessageBox (
    MessageBoxId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SenderId INT NOT NULL,
    ReceiverId INT NOT NULL,
    CarId INT NOT NULL,
    Subject NVARCHAR(200) NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    SentDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    IsRead BIT NOT NULL DEFAULT 0,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Message_Sender FOREIGN KEY (SenderId) REFERENCES Users(UserId),
    CONSTRAINT FK_Message_Receiver FOREIGN KEY (ReceiverId) REFERENCES Users(UserId),
    CONSTRAINT FK_Message_Car FOREIGN KEY (CarId) REFERENCES Car(CarId)
);
GO

CREATE TABLE Sale (
    SaleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CarId INT NOT NULL,
    ClientId INT NOT NULL,
    SaleDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    FinalPrice DECIMAL(18,2) NOT NULL,
    PaymentMethod NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_Sale_Car FOREIGN KEY (CarId) REFERENCES Car(CarId),
    CONSTRAINT FK_Sale_Client FOREIGN KEY (ClientId) REFERENCES Client(ClientId)
);
GO